INSERT INTO "SYSTEM"."MASCHINEN" (MASCH_NR) VALUES ('61282649');
INSERT INTO "SYSTEM"."MASCHINEN" (MASCH_NR) VALUES ('61282634');
INSERT INTO "SYSTEM"."MASCHINEN" (MASCH_NR) VALUES ('61282630');
INSERT INTO "SYSTEM"."MASCHINEN" (MASCH_NR) VALUES ('61542722');
INSERT INTO "SYSTEM"."MASCHINEN" (MASCH_NR) VALUES ('61542721');

INSERT INTO "SYSTEM"."AUFTRAGS_BESTAND" (AUFTRAG_NR, MASCH_NR, VERWEIS, BEARB_DATE) VALUES ('1', '61282649', '1', TO_DATE('2015-10-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO "SYSTEM"."AUFTRAG_STATUS" (AUFTRAG_NR, A_STATUS, MASCH_NR) VALUES ('1', 'E', '61282649');

INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1001');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1002');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1003');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1004');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1005');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1006');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1007');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1008');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1009');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1010');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1011');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('1012');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2001');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2002');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2003');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2004');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2005');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2006');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2007');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2008');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2009');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2010');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2011');
INSERT INTO "SYSTEM"."ADE_GRUND_TEXTE" (GRUNDTEXT_NR) VALUES ('2012');

INSERT INTO "SYSTEM"."ADE_AUFTRAGMENGEN" (AUFTRAG_NR, GRUND_TEXT) VALUES ('1', '1001');
